import tkinter as tk
from tkinter import *
from GT1000 import GT1000

class debugWindow(Frame):

  def updateOutputsCmd__click(self):
    print("[call] updateOutputsCmd__click()")
    print("[end call] updateOutputsCmd__click()")

  def updateInputsCmd__click(self):
    print("[call] updateInputsCmd__click()")
    self.GT1000.read_inputs()
    self.StartChkStatus.set(GT1000.GT_Start)
    self.AbortChkStatus.set(GT1000.GT_Abort)
    self.LeakChkStatus.set(GT1000.GT_LK)
    self.User2ChkStatus.set(GT1000.GT_UserIn)
    self.bank1chip0Text.set(GT1000.GTchip0int[0])
    self.bank1chip2Text.set(GT1000.GTchip2int[0])
    self.bank1chip3Text.set(GT1000.GTchip3int[0])
    self.bank1chip4Text.set(GT1000.GTchip4int[0])
    self.bank1chip6Text.set(GT1000.GTchip6int[0])
    print("[end call] updateInputsCmd__click()")


  def __init__(self, master=None):
    print("<NEW> Initializing debugWindow...")
    Frame.__init__(self,master)
    self.pack(fill=BOTH, expand=1)

    self.GT1000 = GT1000()

    #exitCmd = Button(self, text="Exit", command=self.clickExitCmd, height=2, width=1)
    #exitCmd.place(x=0, y=0)

    self.GT1000LblText = StringVar()
    self.bank1chip0Text = StringVar()
    self.bank1chip2Text = StringVar()
    self.bank1chip3Text = StringVar()
    self.bank1chip4Text = StringVar()
    self.bank1chip6Text = StringVar()
    self.bank2chip0Text = StringVar()
    self.bank2chip2Text = StringVar()
    self.bank2chip3Text = StringVar()
    self.bank2chip4Text = StringVar()
    self.bank2chip6Text = StringVar()
    self.bank3chip0Text = StringVar()
    self.bank3chip2Text = StringVar()
    self.bank3chip3Text = StringVar()
    self.bank3chip4Text = StringVar()
    self.bank3chip6Text = StringVar()
    self.bank1chip0Text.set("0x10")
    self.bank1chip2Text.set("0x12")
    self.bank1chip3Text.set("0x13")
    self.bank1chip4Text.set("0x14")
    self.bank1chip6Text.set("0x16")
    self.bank2chip0Text.set("0x20")
    self.bank2chip2Text.set("0x22")
    self.bank2chip3Text.set("0x23")
    self.bank2chip4Text.set("0x24")
    self.bank2chip6Text.set("0x26")
    self.bank3chip0Text.set("0x30")
    self.bank3chip2Text.set("0x32")
    self.bank3chip3Text.set("0x33")
    self.bank3chip4Text.set("0x34")
    self.bank3chip6Text.set("0x36")
    self.GT1000LblText.set("None")

    # Output section; labels
    outputsLbl = Label(self, text="Outputs",width=10,font=('Arial',12,'bold'))
    GPIOLbl = Label(self, text="GPIO",width=10,font=('Arial',10,'bold'))
    updateOutputsCmd = Button(self, text="Update Outputs",command=self.updateOutputsCmd__click,width=12,height=3).place(x=0,y=250)
    updateInputsCmd = Button(self, text="Update Inputs",command=self.updateInputsCmd__click,width=12,height=3).place(x=0,y=320)
    inputsLbl = Label(self, text="Inputs",font=('Arial',12,'bold'),anchor="center")
    chip0Lbl = Label(self, text="Chip 000")
    chip1Lbl = Label(self, text="Chip 001")
    chip2Lbl = Label(self, text="Chip 010")
    chip3Lbl = Label(self, text="Chip 011")
    chip4Lbl = Label(self, text="Chip 100")
    chip6Lbl = Label(self, text="Chip 110")
    bank1Lbl = Label(self, text="Bank 1", font=('Arial',10,'bold'))
    bank1chip0Lbl = Entry(self, textvariable=self.bank1chip0Text,width=12)
    bank1chip2Lbl = Entry(self, textvariable=self.bank1chip2Text,width=12)
    bank1chip3Lbl = Entry(self, textvariable=self.bank1chip3Text,width=12)
    bank1chip4Lbl = Entry(self, textvariable=self.bank1chip4Text,width=12)
    bank1chip6Lbl = Entry(self, textvariable=self.bank1chip6Text,width=12)
    bank2Lbl = Label(self, text="Bank 2", font=('Arial',10,'bold'))
    bank2chip0Lbl = Entry(self, textvariable=self.bank2chip0Text,width=12)
    bank2chip2Lbl = Entry(self, textvariable=self.bank2chip2Text,width=12)
    bank2chip3Lbl = Entry(self, textvariable=self.bank2chip3Text,width=12)
    bank2chip4Lbl = Entry(self, textvariable=self.bank2chip4Text,width=12)
    bank2chip6Lbl = Entry(self, textvariable=self.bank2chip6Text,width=12)
    bank3Lbl = Label(self, text="Bank 3", font=('Arial',10,'bold'))
    bank3chip0Lbl = Entry(self, textvariable=self.bank3chip0Text,width=12)
    bank3chip2Lbl = Entry(self, textvariable=self.bank3chip2Text,width=12)
    bank3chip3Lbl = Entry(self, textvariable=self.bank3chip3Text,width=12)
    bank3chip4Lbl = Entry(self, textvariable=self.bank3chip4Text,width=12)
    bank3chip6Lbl = Entry(self, textvariable=self.bank3chip6Text,width=12)
    GPIOInLbl = Label(self, text="GPIO Inputs", font=('Arial',10,'bold'))
    GT1000Lbl = Label(self, textvariable=self.GT1000LblText)

    outputsLbl.place(x=0, y=0)
    GPIOLbl.place(x=0, y=25)

    inputsLbl.place(x=500,y=0)
    chip0Lbl.place(x=200,y=25)
    chip2Lbl.place(x=320,y=25)
    chip3Lbl.place(x=440,y=25)
    chip4Lbl.place(x=560,y=25)
    chip6Lbl.place(x=680,y=25)
    bank1Lbl.place(x=500,y=50)
    bank1chip0Lbl.place(x=200,y=75)
    bank1chip2Lbl.place(x=320,y=75)
    bank1chip3Lbl.place(x=440,y=75)
    bank1chip4Lbl.place(x=560,y=75)
    bank1chip6Lbl.place(x=680,y=75)
    bank2Lbl.place(x=500,y=125)
    bank2chip0Lbl.place(x=200,y=150)
    bank2chip2Lbl.place(x=320,y=150)
    bank2chip3Lbl.place(x=440,y=150)
    bank2chip4Lbl.place(x=560,y=150)
    bank2chip6Lbl.place(x=680,y=150)
    bank3Lbl.place(x=500,y=200)
    bank3chip0Lbl.place(x=200,y=225)
    bank3chip2Lbl.place(x=320,y=225)
    bank3chip3Lbl.place(x=440,y=225)
    bank3chip4Lbl.place(x=560,y=225)
    bank3chip6Lbl.place(x=680,y=225)
    GPIOInLbl.place(x=500,y=275)

    GT1000Lbl.place(x=550,y=425)

    # Output Components
    self.PassChkStatus = IntVar()
    self.FailChkStatus = IntVar()
    self.InTestChkStatus = IntVar()
    self.User1ChkStatus = IntVar()
    self.Bank1ChkStatus = IntVar()
    self.Bank2ChkStatus = IntVar()
    self.Bank3ChkStatus = IntVar()
    self.Bank4ChkStatus = IntVar()
    self.StartChkStatus = IntVar()
    self.AbortChkStatus = IntVar()
    self.LeakChkStatus = IntVar()
    self.User2ChkStatus = IntVar()
    PassChk = Checkbutton(self, text="Pass",variable=self.PassChkStatus).place(x=0,y=125)
    FailChk = Checkbutton(self, text="Fail",variable=self.FailChkStatus).place(x=0,y=50)
    InTestChk = Checkbutton(self, text="In Test",variable=self.InTestChkStatus).place(x=0,y=75)
    User1Chk = Checkbutton(self, text="User 1",variable=self.User1ChkStatus).place(x=0, y=100)
    Bank1Chk = Checkbutton(self, text="Bank 1",variable=self.Bank1ChkStatus).place(x=0, y=150)
    Bank2Chk = Checkbutton(self, text="Bank 2",variable=self.Bank2ChkStatus).place(x=0, y=175)
    Bank3Chk = Checkbutton(self, text="Bank 3",variable=self.Bank3ChkStatus).place(x=0, y=200)
    StartChk = Checkbutton(self, text="Start",variable=self.StartChkStatus).place(x=200, y=300)
    AbortChk = Checkbutton(self, text="Abort",variable=self.AbortChkStatus).place(x=320, y=300)
    LeakChk = Checkbutton(self, text="Leak",variable=self.LeakChkStatus).place(x=440,y=300)
    User2Chk = Checkbutton(self, text="User 2",variable=self.User2ChkStatus).place(x=560,y=300)

    # Call update functions
    self.updateInputsCmd__click()

#    q38Cmd = Button(self, text="Read 0x38", command=self.clickQ38Cmd, width=10)
#    q38Cmd.place(x=5,y=5)
#    q39Cmd = Button(self, text="Read 0x39", command=self.clickQ39Cmd, width=10)
#    q39Cmd.place(x=200,y=100)
#    q3aCmd = Button(self, text="Read 0x3a", command=self.clickQ3aCmd, width=10)
#    q3aCmd.place(x=400,y=200)

  def clickExitCmd(self):
    exit()

  def clickQ38Cmd(self):
    print("clickQ38Cmd")

  def clickQ39Cmd(self):
    print("clickQ39Cmd")

  def clickQ3aCmd(self):
    print("clickQ3aCmd")

